const HIGH_INTENSITY_NEGATIVE_REACTIONS = ["anguish"]
const LOW_INTENSITY_NEGATIVE_REACTIONS = ["frown"]
const HIGH_INTENSITY_POSITIVE_REACTIONS = ["laugh", "taunt"]
const LOW_INTENSITY_POSITIVE_REACTIONS = ["smile"]
